services:
    gateway-service:
        build: ./gateway-service
        ports:
            - "8080:8080"
        environment:
            GATEWAY_SERVICE_UPLOAD_DIR: /app/uploads
            GATEWAY_SERVICE_DB_URL: ${DATABASE_URL_DOCKER}
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - uploads_data:/app/uploads

    postgres:
        image: postgres:16-alpine
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
          interval: 5s
          timeout: 5s
          retries: 3
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    
volumes:
    postgres_data:
    uploads_data:

